# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: sfpwowerscript-installsfdx-task@9
  inputs:
   isTelemetryEnabled: true
- task: sfpwowerscript-authenticateorg-task@9
  inputs:
    method: 'Credentials'
    username: '$(SalesforceUsername)'
    password: '$(SalesforcePassword)'
    securitytoken: '$(SalesforceSecurityToken)'
    alias: '$(Alias)'
    isdevhub: false
- task: sfpowerscript-exportsourcefromorg-task@3
  inputs:
    target_org: '$(Alias)'
    source_directory: 'salesforce'
    isManagedPackageComponentsToBeExcluded: false
    isUnzipEnabled: false
